<?php

namespace App\Observers;

use App\Models\Plan;
use Illuminate\Support\Str;

class PlanObserver
{
    /**
     * Handle the plan "creating" event.
     *
     * @param  \App\Models\Plan  $plan
     * @return void
     */
    public function creating(Plan $plan)
    {
        if (blank($plan->url)) {
        $plan->url = Str::kebab($plan->name);
        } else {
            $plan->url = Str::kebab($plan->url);
        }
    }

    /**
     * Handle the plan "updating" event.
     *
     * @param  \App\Models\Plan  $category
     * @return void
     */
    public function updating(Plan $plan)
    {
        if ($plan->isDirty('url')) {
            $plan->url = Str::kebab($plan->url);
            return;
        }

        if ($plan->isDirty('name')) {
            $originalUrl = $plan->getOriginal('url');
            $originalName = $plan->getOriginal('name');
            $wasAutoGenerated = blank($originalUrl) || $originalUrl === Str::kebab($originalName);

            if ($wasAutoGenerated) {
        $plan->url = Str::kebab($plan->name);
            }
        }
    }
}
